# Generated by Django 5.0.6 on 2024-07-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="eid",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="node",
            name="nid",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="edge",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
